version: '1.0'

services:
  nodelogin:
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./:/home/app/
    command: "nodemon --legacy-watch index.js"
    # image: node:19-alpine3.16
    # working_dir: /home/app/
    # ports:
    #   - 3000:3000
    # volumes:
    #   - ./:/home/app/
    # command: sh -c "yarn install && yarn global add nodemon && nodemon --legacy-watch index.js"
    # stdin_open: true 
    # tty: true

  db:
    image: mysql:8.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: hola123
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: userdata
    ports:
      - 5606:3360
    expose:
      - 3306
    volumes:
      - ./sqlinit:/docker-entrypoint-initdb.d

  phpmyadmin:
      image: phpmyadmin:5.2
      restart: always
      ports:
        - 8080:80
      environment:
        PMA_HOST: db
        PMA_PORT: 3306
        PMA_ARBITRARY: 1


